
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [main] 
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
jobs:
  build:
    runs-on: [ ubuntu-latest]
    steps:
      - run: 'echo ${{ github.event_name }}'
      - run: 'echo ${{ github.branch }}'
      - run: 'ls ${{ github.workspace }}'
      

  
  
